cloneConcurrency: 8

enableProgressBars: true

enableStrictSsl: true

enableTelemetry: false

enableTimers: true

enableTransparentWorkspaces: false

initFields:
  version: 0.0.0
  author:
    email: amit.prakash.ambasta@gmail.com
    name: Amit Ambasta
    url: "https://github.com/ambasta"
  bugs: "https://github.com/delhivery/nestmikrorepro/issues"
  devDependencies:
    tslib: ^2.4.1
    typescript: ^4.9.4
  engines:
    yarn: ">=4.0.0-rc.32"
  homepage: "https://github.com/delhivery/nestmikrorepro"
  license: UNLICENSED
  main: dist/index.js
  repository:
    type: git
    url: "https://github.com/delhivery/nestmikrorepro"
  scripts:
    build: yarn tsc -p tsconfig.build.json
  type: module
  types: dist/index.d.ts

initScope: nestmikrorepro

plugins:
  - checksum: dc69d67379606247ccb2122d20aa1eeb305297b506caf94aeae1766b4a5518038ab48681a3916fda33d8d3a948bd8a59a167273190f2f0458476d866416cf314
    path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"

yarnPath: .yarn/releases/yarn-4.0.0-rc.34.cjs
